### ISSUE TITLE
How to Use and Examples

### ISSUE THREAD

**Issue by marianneR** [olenz/externbib#3]
Is there any documentation on how to use this ExternBib MediaWiki extension?
Are other extensions required?
I would like to see an example of this extension before trying it. Can you provide a link to an example MediaWiki that uses this extension for cite? The example that I have seen will not allow me to view source of the MediaWIki page.

This extension looks like something I could use,  
Thanks for publishing and providing support for this extension.

**Comment by olenz** [comment]
The extension is not really maintained anymore, so you can do with it what you like. 
The only wiki that uses it is the wiki of my former institute: http://www.icp.uni-stuttgart.de/~icp/Main_Page
You can see it working here: http://www.icp.uni-stuttgart.de/~icp/Christian_Holm

The extension is standalone, as I have included all code that is needed.

As you are not able to look at the sources, this is the "code" that generates a list of citations. You simply have to give the bibtex keys:
```<bibentry pdflink="yes">
bauer14a,
dommert14a,
hickey14a,
kesselheim14a,
krishnamoorthy14a,
micciulla14a,
raafatnia14a,
smiatek14a,
smiatek14d,
vagias14a
</bibentry>```

To get it to work, there are a number of configuration variables in https://github.com/olenz/externbib/blob/master/ExternBib.php that you can modify in you settings file to specify where to find the various files and directories, and the base URL of your site.

The fundamental principle of the extension is that a bibtex file is translated to a dba-file using the PHP-script "updatedb.php". This dba-file is then used from the extension.

Good luck with the extension! It is far from being perfect, but it worked for us for several years without major pain.

**Comment by olenz** [comment]
Oh, and I would be happy if my work would be reused by someone else!
